#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
exec-once = hyprpanel
exec-once=waypaper --restore
exec-once=/home/shaiikura/.config/waypaper/autopicker.sh
exec-once = discordcanary --start-minimized
exec-once = ~/.config/hypr/2_workspace.sh
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = hypridle
exec-once = steam -silent
exec-once = bash -c 'sshfs reub0524@arc-login.arc.ox.ac.uk:/data/biol-synoxys-epi/reub0524 /home/shaiikura/biol-synoxys-epi'
