#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = hyprpanel
exec-once=waypaper --restore
exec-once=/home/shaiikura/.config/waypaper/autopicker.sh
exec-once = flatpak run com.discordapp.DiscordCanary --start-minimized
exec-once = ~/.config/hypr/start_monitor.sh >> ~/start-monitor.log
exec-once = tmux new-session -d ~/.config/hypr/handle_monitor_connect.sh
exec-once = tmux new-session -d ~/.config/hypr/handle_monitor_disconnect.sh
exec-once = ~/.config/hypr/scripts/change_wallpaper.sh
exec-once =~/.config/hypr/scripts/copy_hyprlock.sh
# exec-once = onedrivegui -q
