#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = hyprpanel
# exec-once = discordcanary --start-minimized
exec-once = /home/shaiikura/.config/hypr/start_monitor.sh >> /home/shaiikura/start-monitor.log
exec-once = /home/shaiikura/.config/waypaper/autopicker.sh
exec-once = /home/shaiikura/.config/hypr/handle_monitor_connect.sh >> /home/shaiikura/start-connect.log
exec-once = /home/shaiikura/.config/hypr/handle_monitor_disconnect.sh >> /home/shaiikura/start-disconnect.log
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = timeout 10s bash -c 'sshfs reub0524@arc-login.arc.ox.ac.uk:/data/biol-synoxys-epi/reub0524 /home/shaiikura/biol-synoxys-epi'
