################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,1920x1080,-1920x0,1
monitor=desc:Dell Inc. DELL S2721DS 9ZT0VY3,2560x1440,0x0,1
monitor = , preferred, auto, 1

# Bind workspaces 1-5 to the Dell monitor
workspace = 1, monitor:desc:Dell Inc. DELL S2721DS 9ZT0VY3, default:true
workspace = 2, monitor:desc:Dell Inc. DELL S2721DS 9ZT0VY3, default:true
workspace = 3, monitor:desc:Dell Inc. DELL S2721DS 9ZT0VY3, default:true
workspace = 4, monitor:desc:Dell Inc. DELL S2721DS 9ZT0VY3, default:true
workspace = 5, monitor:desc:Dell Inc. DELL S2721DS 9ZT0VY3, default:true

# Bind workspaces 6-10 to the eDP-1 monitor
workspace = 6, monitor:eDP-1, default:true
workspace = 7, monitor:eDP-1, default:true
workspace = 8, monitor:eDP-1, default:true
workspace = 9, monitor:eDP-1, default:true
workspace = 10, monitor:eDP-1, default:true

