################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,1920x1080,-1920x0,1
monitor=desc:Dell Inc. DELL S2721DS 9ZT0VY3,2560x1440,0x0,1
monitor = , preferred, auto, 1
