{...}: {
  imports = [
    ./assistant.nix
    ./autoActions.nix
    ./binds.nix
    ./clipboard.nix
    ./dashboard.nix
    ./diagnostics.nix
    ./git.nix
    ./harperSpellCheck.nix
    ./keymaps.nix
    ./languages.nix
    ./minimap.nix
    ./neotree.nix
    ./notes.nix
    ./notify.nix
    ./plugins.nix
    ./projects.nix
    ./rSpecificSettings.nix
    ./snippets.nix
    ./statusline.nix
    ./telescope.nix
    ./theme.nix
    ./toggleterm.nix
    ./treesitter.nix
    ./ui.nix
    ./utility.nix
    ./visuals.nix
  ];
}
