# Do not modify this file!  It was generated by ‘nixos-generate-config’
{
  config,
  pkgs,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    extraModprobeConfig = ''
      options it87 force_id=0x8622
    '';
    kernelPackages = pkgs.linuxPackages_zen;

    loader = {
      grub = {
        enable = true;
        efiSupport = true;
        devices = ["nodev"];
        useOSProber = true;
      };
      efi.canTouchEfiVariables = true;
      timeout = 5;
    };
    initrd = {
      verbose = false;
      availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
      kernelModules = ["kvm-amd"];
    };
    kernel.sysctl = {
      "vm.swappiness" = 10;
    };
    kernelParams = [
      "acpi_enforce_resources=lax"
    ];
    kernelModules = [
      "k10temp"
      "it87"
      "i2c-dev"
    ];
    supportedFilesystems = ["ntfs"];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7d53fa8e-e0ca-46b0-982b-6e75f2b5e35b";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/DB26-EC58";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/mnt/windows" = {
    device = "/dev/disk/by-uuid/943AB5D03AB5B01A";
    fsType = "ntfs";
  };

  fileSystems."/mnt/games" = {
    device = "/dev/disk/by-uuid/F69C7E789C7E336B";
    fsType = "ntfs-3g";
    options = ["rw" "uid=1000"];
  };

  fileSystems."/home/shaiikura/externalUbisoft" = {
    depends = [
      "/home/shaiikura"
      "/mnt/games"
    ];
    device = "/mnt/games/Ubisoft";
    fsType = "none";
    options = [
      "bind"
    ];
  };

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = true;
  hardware.enableRedistributableFirmware = true;
}
