# Do not modify this file!  It was generated by ‘nixos-generate-config’
{ 
  config,
  pkgs,
  lib,
  modulesPath, 
  ... 
}:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];


  boot = {
    kernelPackages = pkgs.linuxPackages_zen;

    loader = {
      grub = {
        enable = true;
        efiSupport = true;
        devices = [ "nodev" ];
        useOSProber = true;
      };
      efi.canTouchEfiVariables = true;
      timeout = 0;
    };
    initrd = {
      verbose = false;
      availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
      kernelModules = [ "dm-snapshot" ];
      luks.devices.luks-root = {
        device = "/dev/disk/by-uuid/18259c3e-e044-4752-86ea-b5f79fd1463c";
        preLVM = true;
      };
    };
    kernel.sysctl = {
      "vm.swappiness" = 10;
    };
    kernelParams = [
    ];
    kernelModules = [
      "kvm-intel"
    ];
  };
  
  fileSystems."/" =
    { device = "/dev/vg/root";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1A2E-3DAB";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # For mount.cifs, required unless domain name resolution is not needed.
  fileSystems."/mnt/geldoc" = {
    device = "//10.200.62.89/Share";
    fsType = "cifs";
    options = let
      # this line prevents hanging on network split
      automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";

    in ["${automount_opts},credentials=/run/secrets/geldoc"];
  };

  swapDevices =
    [ { device = "/dev/vg/swap"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
