# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernel.sysctl = {
    "vm.swappiness" = 10;
  };
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/vg/root";
      fsType = "ext4";
    };

  # fileSystems."/mnt/biol-synoxys" = {
  #   device = "reub0524@arc-login.arc.ox.ac.uk:/data/biol-synoxys";
  #   fsType = "sshfs";
  #   options = [
  #     "x-systemd.automount"
  #     "noauto"
  #     "IdentityFile=/home/shaiikura/.ssh/id_ed25519"
  #   ];
  # };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1A2E-3DAB";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # For mount.cifs, required unless domain name resolution is not needed.
  fileSystems."/mnt/geldoc" = {
    device = "//10.200.62.89/Share";
    fsType = "cifs";
    options = let
      # this line prevents hanging on network split
      automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";

    in ["${automount_opts},credentials=/run/secrets/geldoc"];
  };

  swapDevices =
    [ { device = "/dev/vg/swap"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = true;
  hardware.enableRedistributableFirmware = true;
}
